#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Deploys the AI Governance Compatibility Checker on a plain Linux VPS
# (Ubuntu/Debian assumed). Run from the repository root as a user with sudo:
#
#     bash deploy/deploy.sh
#
# What it does:
#   1. Verifies Node.js >= 22.13 (installs Node 22 via NodeSource if missing)
#   2. npm install (includes better-sqlite3 for the self-hosted database)
#   3. Creates .env.local with a generated AUTH_SECRET and ADMIN_TOKEN
#      if the file doesn't exist yet
#   4. Builds the app (env vars from .env.local are inlined at build time)
#   5. Installs and starts a systemd service (ai-gov-checker, port 3000)
#
# After it finishes, put HTTPS in front (see deploy/Caddyfile.example).
# Re-running the script is safe: it rebuilds and restarts the service.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_USER="${SUDO_USER:-$(whoami)}"
SERVICE_NAME="ai-gov-checker"

cd "$APP_DIR"
echo "==> Deploying from $APP_DIR as user $APP_USER"

# 1) Node.js -----------------------------------------------------------------
need_node=1
if command -v node >/dev/null 2>&1; then
  major="$(node -p 'process.versions.node.split(".")[0]')"
  minor="$(node -p 'process.versions.node.split(".")[1]')"
  if [ "$major" -gt 22 ] || { [ "$major" -eq 22 ] && [ "$minor" -ge 13 ]; }; then
    need_node=0
  fi
fi
if [ "$need_node" -eq 1 ]; then
  echo "==> Installing Node.js 22 (NodeSource)…"
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi
echo "==> Node $(node --version), npm $(npm --version)"

# better-sqlite3 falls back to compiling from source if no prebuilt binary
# matches; make sure a toolchain exists (no-op if already installed).
if command -v apt-get >/dev/null 2>&1; then
  sudo apt-get install -y --no-install-recommends build-essential python3 >/dev/null
fi

# 2) Dependencies ------------------------------------------------------------
echo "==> Installing dependencies…"
npm install

# 3) Environment -------------------------------------------------------------
if [ ! -f .env.local ]; then
  echo "==> Creating .env.local with generated secrets…"
  AUTH_SECRET_VALUE="$(openssl rand -base64 33)"
  ADMIN_TOKEN_VALUE="$(openssl rand -hex 24)"
  cat > .env.local <<ENV
# Generated by deploy.sh — edit freely, then re-run the script to rebuild.

# Signs/encrypts session cookies (required).
AUTH_SECRET=${AUTH_SECRET_VALUE}

# Protects POST /api/admin/set-plan (x-admin-token header). Use this to flip
# a paying customer's plan:  {"email":"them@example.com","plan":"pro"}
ADMIN_TOKEN=${ADMIN_TOKEN_VALUE}

# Google / Microsoft sign-in (optional — the app works anonymously without it).
# Redirect URIs: https://<your-domain>/api/auth/callback/google
#                https://<your-domain>/api/auth/callback/microsoft-entra-id
AUTH_GOOGLE_ID=
AUTH_GOOGLE_SECRET=
AUTH_MICROSOFT_ENTRA_ID_ID=
AUTH_MICROSOFT_ENTRA_ID_SECRET=

# Where the Upgrade / Contact sales buttons point (e.g. a Stripe Payment Link).
# These are inlined at BUILD time — re-run deploy.sh after changing them.
NEXT_PUBLIC_UPGRADE_URL=
NEXT_PUBLIC_CONTACT_URL=
ENV
  chmod 600 .env.local
  echo "    ADMIN_TOKEN (save this): ${ADMIN_TOKEN_VALUE}"
else
  echo "==> Keeping existing .env.local"
fi

# 4) Build -------------------------------------------------------------------
echo "==> Building…"
set -a
# shellcheck disable=SC1091
. ./.env.local
set +a
npm run build

# 5) systemd service ---------------------------------------------------------
echo "==> Installing systemd service ${SERVICE_NAME}…"
sed -e "s|__APP_DIR__|${APP_DIR}|g" -e "s|__APP_USER__|${APP_USER}|g" \
  deploy/ai-gov-checker.service | sudo tee /etc/systemd/system/${SERVICE_NAME}.service >/dev/null
mkdir -p "${APP_DIR}/data"
sudo systemctl daemon-reload
sudo systemctl enable "${SERVICE_NAME}" >/dev/null
sudo systemctl restart "${SERVICE_NAME}"
sleep 3

if curl -fsS -o /dev/null http://localhost:3000/; then
  echo "==> ✔ Service is up: http://localhost:3000"
  echo "    Next step: HTTPS. Install Caddy (https://caddyserver.com/docs/install),"
  echo "    adapt deploy/Caddyfile.example with your domain, and reload Caddy."
  echo "    Manage the app with: sudo systemctl {status|restart|stop} ${SERVICE_NAME}"
  echo "    Logs: journalctl -u ${SERVICE_NAME} -f"
else
  echo "==> ✖ Service did not respond on :3000. Inspect logs:"
  echo "    journalctl -u ${SERVICE_NAME} -n 50"
  exit 1
fi
